version: 2

base_dbt_profile:
  target: dbt
  outputs:
    dbt:
      threads: 4
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: striped-torus-445510-c9
      schema: dbt
      location: US